from random import randint

def guess(number):
    guess = input("Guess the number: ")
    if(int(guess)==number):
        print("Congrats")
    elif(int(guess)>number):
        print("Too big...")
    elif(int(guess)<number):
        print("Too small...")
    return (int(guess))

game = True
while game == True:
    print("Hello, your task is to guess a number generated by me, good luck! ")
    tries = 1
    range=input('Give me a range seperated by "-", e.g. 1-10 ')
    borders = range.split("-")
    generatedNumber = randint(int(borders[0]), int(borders[1]))
    #print(generatedNumber)
    while generatedNumber != guess(generatedNumber):
        tries += 1
        #print(tries)
    if((input(f"Your have tried {tries} times! \n Want to play again? Y/N ")).lower() == "y"):
        game == True
    else: 
        game = False


    
